cardcollecter/cardcollecter/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_app.urls')),
]

cardcollecter/main_app/urls.py
from django.urls import path
from . import views 



urlpatterns = [
    path('', views.home, name='home'),
    path('about/',views.about, name='about'),
    path('cards/',views.cards_index, name='index'),
    path('cards/<int:card_id>/', views.cards_detail, name='detail'),
    path('cards/create/', views.CardCreate.as_view(), name='Cards_create'),
    path('card/<int:pk>/update/' , views.CardUpdate.as_view(),name='cards_update'),
    path('card/<int:pk>/delete/' , views.CardDelete.as_view(),name='cards_delete'),
    path('card/<int:card_id>/add_market/', views.add_market, name='add_market'),

]

cardcollecter/main_app/models.py
from django.db import models
from django.urls import reverse


MARKET = (
    ('B', 'BGS'),
    ('P', 'PSA'),
    ('C', 'CGC'),
)

# Create your models here.

class Card(models.Model):
    name = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    grade = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'card_id': self.id})


class Market(models.Model):
    date = models.DateField('submission date')
    price = models.CharField(
        max_length=1,
        choices=MARKET,
        default=MARKET[0][0]
    )
    card = models.ForeignKey(
        Card,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.get_price_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

cardcollecter/main_app/forms.py
from django.forms import ModelForm
from .models import Market

class MarketForm(ModelForm):
    class Meta:
        model = Market
        fields = ['date','price']

cardcollecter/main_app/views.py
# main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Import the Card Model
from .models import Card
from .forms import MarketForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cards_index(request):
    cards = Card.objects.all()
    return render(request, 'cards/index.html', {
    'cards': cards
  })


def cards_detail(request, card_id):
    card = Card.objects.get(id=card_id)
    market_form = MarketForm()
    return render(request, 'cards/detail.html', {
        'card' : card, 'market_form': market_form
    })

class CardCreate(CreateView):
    model = Card 
    fields = '__all__'

class CardUpdate(UpdateView):
    model = Card 
    fields = ['series', 'description', 'grade']

class CardDelete(DeleteView):
    model = Card 
    success_url = '/cards'

def add_market(request, card_id):
    form = MarketForm(request.POST)

    if form.is_valid():
        new_market = form.save(commit=False)
        new_market.card_id = card_id
        new_market.save()
    
    return redirect('detail', card_id=card_id)

cardcollecter/main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}

  <h1>About the Card Collector</h1>
  <hr />
  <p>Hire the Card Collector!</p>
  <footer>All Rights Reserved, &copy; 2022 Card Collector</footer>

{% endblock %}

cardcollecter/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <meta
      http-equiv="X-UA-Compatible"
      content="ie=edge"
    />
    <title>Card Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Card Collector</a></li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'Cards_create' %}">Add A Card</a></li>
            <li><a href="{% url 'index' %}">View All My Cards</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">All Rights Reserved, &copy; 2023 Card Collector &nbsp;</div>
    </footer>
  </body>
</html>

cardcollecter/main_app/templates/cards/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Card Details</h1>

  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ card.name }}</span>
      <p>Series: {{ card.series }}</p>
      <p>Description: {{ card.description|linebreaks }}</p>
      <p>Grade: {{ card.grade }}</p>
    </div>
    <div class="card-action">
      <a href="{% url 'cards_update' card.id %}">Edit</a>
      <a href="{% url 'cards_delete' card.id %}">Delete</a>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_market' card.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ market_form.as_p }}
      <input type="submit" class="btn" value="Add Submission" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Submission Date</th>
          <th>Grading Service</th>
        </tr>
      </thead>
      <tbody>
        {% for market in card.market_set.all %}
        <tr>
          <td>{{market.date}}</td>
          <td>{{market.get_price_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

<script>
const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_price');
  M.FormSelect.init(selectEl);
</script>


{% endblock %}

cardcollecter/main_app/templates/cards/index.html
{% extends 'base.html' %} {% block content %}
<h1>Card List</h1>

{% for card in cards %}
<a href="/cards/{{ card.id }}">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ card.name }}</span>
    <p>Series: {{ card.series }}</p>
    <p>Description: {{ card.description|linebreaks }}</p>
    <p>Grade: {{ card.grade }}</p>
  
</div>
</a>
{% endfor %} {% endblock %}

cardcollecter/main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Collecter</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}

    <h1>home</h1>
    {% endblock %}
</body>
</html>

cardcollecter/main_app/templates/main_app/card_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Card</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' card.id %}">Cancel</a>
  </form>
{% endblock %}

cardcollecter/main_app/templates/main_app/card_form.html
{% extends 'base.html' %}

{% block content %}
  
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Card</h1>
  {% endif %}




  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}